apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eshopondapr-pubsub
  namespace: {{ .Values.namespace }}
spec:
# Temporarily use Redis for pub/sub while waiting for https://github.com/dapr/components-contrib/issues/1372 to be released in 1.6.
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: eshopondapr-secrets
      key: RedisPassword
auth:
  secretStore: eshopondapr-secretstore

