apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
spec:
  hosts:
  - {{ .Values.hostName }}
  
  gateways:
  -  {{ .Values.istioGateway }}
  
  http:
  - name: "api-gateway"
    match:
    - uri:
        prefix: /gateway(/|$)(.*)
    rewrite:
      uriRegexRewrite:
        match: "/gateway(/|$)(.*)$"
        rewrite: \2
    route:
    - destination:
        host: apigateway
        port:
          number: 80  

  - name: "identity-api"
    match:
    - uri:
        prefix: "/identity"
    route:
    - destination:
        host: identity-api
        port:
          number: 80  

  - name: "status-api"
    match:
    - uri:
        prefix: "/status"
    route:
    - destination:
        host: webstatus
        port:
          number: 80  

  - name: "log-api"
    match:
    - uri:
        prefix: "/log"
    route:
    - destination:
        host: seq
        port:
          number: 80  

  - name: "default"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: blazor-client
        port:
          number: 80
